### ISSUE TITLE
[Suggestion] Option to show in radians

### ISSUE THREAD

**Issue by Macintosh-Fan** [jpb10/SolarCalculator#21]
Looking at the source code, it does appear to show the values being converted from radians to degrees. The suggestion is to define an optional `bool` parameter to return the values in radians instead of degrees (not sure if this feature is necessary, but I wonder about losing decimal places for `rad -> deg -> rad`, like converting the returned `double` values back into radians, due to floating-point problems).

**Comment by jpb10** [comment]
In a single conversion from `rad -> deg`, the roundoff error is negligible (~0.000015 degrees) compared to the accuracy of the calculation (0.01 degrees). The final results, in degrees, should be rounded to two decimal places.

If you're worried about error propagation, then a proper error analysis must be done. Check out this document by David Brooks: https://instesre.org/ArduinoUnoSolarCalculations.pdf

Since it's not the first time precision has been brought up, I'm working on my own error analysis.
