### ISSUE TITLE
Civil, Nautical, Astronomical Twilight wonky?

### ISSUE THREAD

**Issue by grsmith26** [jpb10/SolarCalculator#22]
I am getting incorrect values for Astronomical dawn, and for both Civil and Nautical dusk.  The following values are for location 33.386854212167975, -111.64819464040542 on date 3/9/2023.

Astr 5:51 (should start about 5:23, and notice it's the same as Naut)
Naut 5:51
Civil 6:20 

Sunrise 6:44 
Transit 12:37 
Sunset 18:29 

Civil 18:54 (should start about 18:30, obviously)
Naut 19:23 (should start 18:55, and notice it's the same as Astr)
Astr 19:23

Everything else above is within round-off allowance.  So, very good!

The code can be viewed/run here:
https://wokwi.com/projects/358710780536496129

**Comment by jpb10** [comment]
The results are actually as expected... see lines 17 to 19:

```
calcCivilDawnDusk(scYear, scMonth, scDay, latitude, longitude, transit, cdawn, cdusk);
calcNauticalDawnDusk(scYear, scMonth, scDay, latitude, longitude, transit, ndawn, ndusk);
calcNauticalDawnDusk(scYear, scMonth, scDay, latitude, longitude, transit, adawn, adusk);
```

Program's output with line 19 changed to `calcAstronomicalDawnDusk`:
```
Astr 5:22, Naut 5:51, Civil 6:20 
Sunrise 6:44 
Transit 12:37 
Sunset 18:29 
Civil 18:54, Naut 19:23, Astr 19:52 
```

Compare with: https://www.timeanddate.com/sun/@33.386854212167975,-111.64819464040542

In the morning, the times are when twilight begins; and in the evening, when twilight ends. (Otherwise, it's just a repeat of the previous event, e.g. civil twilight starts at sunset, and so on.) The events occur when the Sun is at the following elevations:

Civil twilight: -6.0 degrees
Nautical twilight: -12.0 degrees
Astronomical twilight: -18.0 degrees

**Comment by grsmith26** [comment]
Copy/paste/modify gets me again.  I regret wasting your time and thank you for the generous correction of my mistake.  Great library.

**Comment by jpb10** [comment]
No problem!
