### ISSUE TITLE
[Suggestion] More UTC timestamps

### ISSUE THREAD

**Issue by Macintosh-Fan** [jpb10/SolarCalculator#9]
For example, could the function `calcSunriseSunset(...)`, and some others, make the values in UTC timestamps instead of hours of the day?

**Comment by jpb10** [comment]
I use something like this:
```
// Convert hours to time
time_t hoursToTime(double h, time_t d)
{
  return previousMidnight(d) + time_t(round(h* 3600));
}
```

**Comment by Macintosh-Fan** [comment]
Cool. Do you think you'll add it as a standard feature in this library in the future or not?

**Comment by getoledo** [comment]
Hello, 
Nice job !
I am testing the library, and there is something I don´t understand
If I use the example "SunriseSunset" with latitude = 40.457497 , longitude = -3.454602,  utc_offset = 1 , the sunrise outputs is  08:19 hs.
Then, if now I use example "SolarTrackingTimeLib" with same coordinates, and // Set time manually (hr, min, sec, day, mo, yr)
  setTime(8, 19, 0, 2, 12, 2022) (same sunrise hour  as in the previous example), this result in Elevation of :8.84º instead of 0º according to sunrise.
There is an error of 1 hour in some place, because if I use setTime(7 19, 0, 2, 12, 2022) (7:19hs)  this gives me an Elevation of -0.33 (sunrise)
Can you help me to figure it out ?

By the way, in same example if I change utc_offset , nothing happens... what should happen?

Thanks !

**Comment by getoledo** [comment]
Hello
Sorry, but can you explain more in detail this?
I don`t understand difference between " UTC timestamps" and "hours of the day".
(this could be related to the "different sunrise results using two different examples of the library" discussion that I just started )

Thank you !

**Comment by jpb10** [comment]
> Hello Sorry, but can you explain more in detail this? I don`t understand difference between " UTC timestamps" and "hours of the day". (this could be related to the "different sunrise results using two different examples of the library" discussion that I just started )
> 
> Thank you !

UTC timestamp (Unix time or Epoch time) is the count of seconds since 0h UT 1 January 1970. 

The "hours of the day" is the time past 0h UT of the current day, in decimal hours.

See this [reply](https://github.com/jpb10/SolarCalculator/discussions/14#discussioncomment-4296138).

**Comment by jpb10** [comment]
I'm closing this issue because this suggestion will be taken into account in a new library for calculating planetary positions.
